### ISSUE TITLE
/etc/default/wildfly.conf should be named /etc/default/wildfly

### ISSUE THREAD

**Issue by bcsmith-fs** [bdwyertech/chef-wildfly#23]
The init script does not read in the default file so changes made like which standalone-ha.conf file are not read in correctly.

**Comment by bcsmith-fs** [comment]
https://github.com/bdwyertech/chef-wildfly/pull/24 Will fix the issue.

**Comment by bdwyertech** [comment]
Thank you for pointing this out, @bcsmith-fs I went ahead and brought the Debian init script in-line with its RHEL counterpart, as the changes in #24 would break RHEL.
