### ISSUE TITLE
cookbook fails if we have LDAP based users

### ISSUE THREAD

**Issue by csmunuku** [bdwyertech/chef-wildfly#27]
wildfly cookbook creates the user and group based on the user and group attributes we set in the attributes file.  But it fails if the user is an LDAP based service account.  Essentially the recipe checks to see if the user entry exists in /etc/passwd.  For LDAP based accounts, the user account entry wouldn't exist in the /etc/passwd.  But when you query for the user, the user exists..   This can be solved in two ways..
1. Give the user attributes to help choose whether to create the user account as part of the recipe OR
2. Help change the logic to see if the user exists before proceeding with user creation.

For the 1 part, I made the necessary changes to the install recipe (and attributes file) and did a pull request.  Please review that and you can either accept the changes  OR please help address this in the 'wildfly' cookbook with your custom implementation..

Really appreciate if you can help with this.

**Comment by bdwyertech** [comment]
I'll try and visit this sometime in the future. I cannot provide a timeframe as I am jammed up with work right now, and WildFly is no longer in my app stack. For now, I'd suggest you simply fork and modify to your liking. I never really intended for this cookbook to be used with an LDAP user.

**Comment by NoellyB76** [comment]
@bdwyertech Hey there Brian, I'm trying to get in touch with you on a wholly unrelated issue. As I'm sure you're aware, GitHub doesn't have a direct messaging feature (go figure), so us dev's can't just reach out without doing something akin to what I'm doing here. That's true, unless I'm missing something.

Anyway, codernoel@gmail.com is me - can you send me a "hey, what's up?" message so I can discuss this with you? It's about a vagrant package you recently released that I'm interested in, and potentially hiring you as a result of.

Thanks,

Noel

**Comment by bdwyertech** [comment]
Hopefully the rewrite helps out with this
