### ISSUE TITLE
Change attribute value

### ISSUE THREAD

**Issue by jeusdi** [bdwyertech/chef-wildfly#46]
I need to change `add-logging-api-dependencies`.

Currently, I'm changing it connecting to wildfly using console:

    /subsystem=logging:write-attribute(name=add-logging-api-dependencies,value=false)

Is there any way to set it to false when I install wildfly using this recipe?

**Comment by jeusdi** [comment]
Any ideas?

**Comment by davidfuhr** [comment]
How about using the attribute resource?

```ruby
wildfly_attribute 'add-logging-api-dependencies' do
   path '/subsystem=logging'
   parameter 'add-logging-api-dependencies'
   value false
end
```

**Comment by jeusdi** [comment]
Almost there:

    value "false"

Thanks
