### ISSUE TITLE
Increate memory settings

### ISSUE THREAD

**Issue by jeusdi** [bdwyertech/chef-wildfly#50]
Is there any way to set memory settings up?

I mean, by default wildfly is configured with these options in `/opt/wildfly/bin/standalone.conf`:

    JAVA_OPTS="-Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true"

I'd like to install wildfly and configure it inder to increase these values.

Is it possible?

**Comment by rbellamy** [comment]
Take a look at [attributes/java_opts.rb](https://github.com/bdwyertech/chef-wildfly/blob/master/attributes/java_opts.rb).
