### ISSUE TITLE
java cookbook version dependency 

### ISSUE THREAD

**Issue by bartoszlew** [bdwyertech/chef-wildfly#62]
Java dependency pinned to ~> 1.22 version in "metadata.rb"  is creating dependency conflicts  when you won't to use new java cookbook eg. 2.0.1
This cookbook works with newer Java cookbook versions (tested on 2.0.1), 
so I'm assuming this is not needed anymore.
Could you please remove java cookbook dependency version?

**Comment by bdwyertech** [comment]
Yeah I agree no need for that anymore...

I'm contemplating yanking Java out as a dependency altogether and moving it into the test cookbook instead.

**Comment by bartoszlew** [comment]
yes, I think that is most proper way to do it. thanks in advance :)

**Comment by bdwyertech** [comment]
Fixed by #63
