### ISSUE TITLE
Chef 15 compatibility

### ISSUE THREAD

**Issue by Sapr0** [bdwyertech/chef-wildfly#72]
According to this document https://docs.chef.io/deprecations_resource_name_without_provides/

Every provider needs to look like:

```
resource_name :wildfly
provides      :wildfly
```

With Chef 16 this already fails as it doesn't find `wildfly` provider

I can help submit a PR if needed

**Comment by bdwyertech** [comment]
@Sapr0 sorry for the delayed response, I will definitely get this added in short order, likely within a week.  Been dealing with this same thing internally.

**Comment by waltwood** [comment]
Hi @bdwyertech, as far as I can tell this hasn't made it to Chef Supermarket yet and I was wondering if this will be available any time in the near future. No problem either way, I'm just trying to decide how to plan around an upgrade to Chef 15+. Thanks!

**Comment by Sapr0** [comment]
@waltwood the github api workflow failed on ubuntu14 so that's why there was no release, probably a bug of some sort.

However in your Berksfile you can point the cookbook directly to the git repo instead of Supermarket and it will pick up the 2.5.0 version
